################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
board/CubeMX_Config/Src \
board \
build/applications \
build/board/CubeMX_Config/Src \
build/board \
build/keil/Obj \
build/kernel/components/drivers/i2c \
build/kernel/components/drivers/ipc \
build/kernel/components/drivers/misc \
build/kernel/components/drivers/rtc \
build/kernel/components/drivers/serial \
build/kernel/components/finsh \
build/kernel/components/libc/compilers/common \
build/kernel/components/libc/compilers/newlib \
build/kernel/libcpu/arm/common \
build/kernel/libcpu/arm/cortex-m4 \
build/kernel/src \
build/libraries/Board_Drivers/lcd \
build/libraries/HAL_Drivers \
build/libraries/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc \
build/libraries/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates \
build/libraries/STM32F4xx_HAL/STM32F4xx_HAL_Driver/Src \
libraries/Board_Drivers/lcd \
libraries/HAL_Drivers \
libraries/HAL_Drivers/drv_flash \
libraries/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc \
libraries/STM32F4xx_HAL/CMSIS/Device/ST/STM32F4xx/Source/Templates \
libraries/STM32F4xx_HAL/STM32F4xx_HAL_Driver/Src \
packages/aht10-v2.1.0 \
packages/cJSON-v1.7.17 \
packages/netutils-latest/ntp \
packages/rw007-v2.0.1/example \
packages/rw007-v2.0.1/src \
packages/webclient-v2.2.0/src \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/rtc \
rt-thread/components/drivers/sensors \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi/sfud/src \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/wlan \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/net/lwip/lwip-2.0.3/src/api \
rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping \
rt-thread/components/net/lwip/lwip-2.0.3/src/core \
rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4 \
rt-thread/components/net/lwip/lwip-2.0.3/src/netif \
rt-thread/components/net/lwip/port \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal/impl \
rt-thread/components/net/sal/socket \
rt-thread/components/net/sal/src \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m4 \
rt-thread/src \
. \

